FROM index.docker.io/library/golang:1.23.4-alpine3.21 AS golang
FROM index.docker.io/library/swift:6.0.3 AS swift

FROM golang AS build
WORKDIR /workspace
COPY go.mod go.sum ./
RUN go mod download -x && \
    go install github.com/swaggo/swag/cmd/swag@v1.16.4 && \
    swag init
COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build -o server .

FROM swift AS run
WORKDIR /workspace
COPY problem ./problem
COPY --from=build /workspace/server .
COPY --from=build /workspace/docs ./docs
CMD ./server
EXPOSE 1323
