FROM index.docker.io/library/golang:1.23.4-alpine3.21 AS golang

FROM golang AS build
WORKDIR /workspace
COPY go.mod go.sum ./
RUN go mod download -x && \
    go install github.com/swaggo/swag/cmd/swag@latest && \
    swag init
COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build -o server .

FROM golang AS run
WORKDIR /workspace
COPY problem ./problem
COPY --from=build /workspace/server .
COPY --from=build /workspace/docs ./docs
CMD ./server
EXPOSE 1323
